apiVersion: platform.upbound.io/v1alpha1
kind: App
metadata:
  name: platform-ref-gcp-ghost
  namespace: default
  labels:
    platform.upbound.io/deletion-ordering: enabled
spec:
  compositeDeletePolicy: Foreground
  parameters:
    providerConfigName: platform-ref-gcp-devex
    helm:
      wait: false
    passwordSecretRef:
      namespace: default
      name: platform-ref-gcp-database-mysql-conn
  writeConnectionSecretToRef:
    name: platform-ref-gcp-ghost-conn
