apiVersion: platform.upbound.io/v1alpha1
kind: App
metadata:
  name: platform-ref-gcp-ghost
  namespace: default
  labels:
    platform.upbound.io/deletion-ordering: enabled
spec:
  parameters:
    providerConfigName: platform-ref-gcp-devex
    helm:
      chart:
        name: ghost
        repo: "oci://registry-1.docker.io/bitnamicharts"
        version: "25.0.4"
      wait: false
    passwordSecretRef:
      namespace: default
      name: platform-ref-gcp-database-mysql-conn
