apiVersion: gcp.platform.upbound.io/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: platform-ref-gcp-db-postgres
  namespace: default
spec:
  parameters:
    storageGB: 10
    passwordSecretRef:
      namespace: default
      name: psqlsecret
      key: password
    networkRef:
      id: platform-ref-gcp
  writeConnectionSecretToRef:
    name: platform-ref-gcp-db-conn-postgres
---
apiVersion: v1
data:
  password: dXBiMHVuZHIwY2s1ITMxMzM3
kind: Secret
metadata:
  name: psqlsecret
  namespace: default
type: Opaque
