apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xclusters.gcp.platformref.upbound.io
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: gcp.platformref.upbound.io/v1alpha1
    kind: XCluster
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: upbound-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: XNetwork
            base:
              apiVersion: gcp.platform.upbound.io/v1alpha1
              kind: XNetwork
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.id
                toFieldPath: spec.parameters.id
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: spec.parameters.region
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.deletionPolicy
                toFieldPath: spec.parameters.deletionPolicy
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.providerConfigName
                toFieldPath: spec.parameters.providerConfigName
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.networkSelector
                toFieldPath: spec.compositionSelector.matchLabels[type]

          - name: XGKE
            base:
              apiVersion: gcp.platform.upbound.io/v1alpha1
              kind: XGKE
            connectionDetails:
              - type: FromConnectionSecretKey
                fromConnectionSecretKey: kubeconfig
                name: kubeconfig
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.id
                toFieldPath: metadata.labels[xgke.gcp.platform.upbound.io/cluster-id]
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.id
                toFieldPath: spec.parameters.id
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: spec.parameters.region
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.deletionPolicy
                toFieldPath: spec.parameters.deletionPolicy
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.providerConfigName
                toFieldPath: spec.parameters.providerConfigName
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.id
                toFieldPath: metadata.annotations[crossplane.io/external-name]
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.uid
                toFieldPath: spec.writeConnectionSecretToRef.name
                transforms:
                  - type: string
                    string:
                      fmt: '%s-gke'
                      type: Format
              - type: FromCompositeFieldPath
                fromFieldPath: spec.writeConnectionSecretToRef.namespace
                toFieldPath: spec.writeConnectionSecretToRef.namespace
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.version
                toFieldPath: spec.parameters.version
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.nodes.count
                toFieldPath: spec.parameters.nodes.count
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.nodes.instanceType
                toFieldPath: spec.parameters.nodes.instanceType

          - name: XOss
            base:
              apiVersion: observe.platform.upbound.io/v1alpha1
              kind: XOss
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.deletionPolicy
                toFieldPath: spec.parameters.deletionPolicy
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.id
                toFieldPath: spec.parameters.id
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.operators.prometheus.version
                toFieldPath: spec.parameters.operators.prometheus.version

          - name: XFlux
            base:
              apiVersion: gitops.platform.upbound.io/v1alpha1
              kind: XFlux
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.deletionPolicy
                toFieldPath: spec.parameters.deletionPolicy
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.id
                toFieldPath: spec.parameters.providerConfigName
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.operators.flux.version
                toFieldPath: spec.parameters.operators.flux.version
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.operators.flux-sync.version
                toFieldPath: spec.parameters.operators.flux-sync.version
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.gitops
                toFieldPath: spec.parameters.source

          - name: usageXGkeByXFlux
            base:
              apiVersion: apiextensions.crossplane.io/v1alpha1
              kind: Usage
              spec:
                by:
                  apiVersion: gitops.platform.upbound.io/v1alpha1
                  kind: XFlux
                  resourceSelector:
                    matchControllerRef: true
                of:
                  apiVersion: gcp.platform.upbound.io/v1alpha1
                  kind: XGKE
                  resourceSelector:
                    matchControllerRef: true

          - name: usageXGkeByXOss
            base:
              apiVersion: apiextensions.crossplane.io/v1alpha1
              kind: Usage
              spec:
                by:
                  apiVersion: observe.platform.upbound.io/v1alpha1
                  kind: XOss
                  resourceSelector:
                    matchControllerRef: true
                of:
                  apiVersion: gcp.platform.upbound.io/v1alpha1
                  kind: XGKE
                  resourceSelector:
                    matchControllerRef: true

          - name: usageXGkeByArbitraryLabeledRelease
            base:
              apiVersion: apiextensions.crossplane.io/v1alpha1
              kind: Usage
              spec:
                by:
                  apiVersion: helm.crossplane.io/v1beta1
                  kind: Release
                  resourceSelector:
                    matchLabels:
                      platform.upbound.io/deletion-ordering: enabled
                of:
                  apiVersion: gcp.platform.upbound.io/v1alpha1
                  kind: XGKE
                  resourceSelector:
                    matchControllerRef: true
            readinessChecks:
              - type: None
