apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xclusters.gcp.platformref.upbound.io
spec:
  compositeTypeRef:
    apiVersion: gcp.platformref.upbound.io/v1alpha1
    kind: XCluster
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-platform-ref-gcpcluster
    step: cluster
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: auto-ready
  writeConnectionSecretsToNamespace: upbound-system
