apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xclusters.gcp.platformref.upbound.io
  labels:
    provider: GCP
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: gcp.platformref.upbound.io/v1alpha1
    kind: XCluster
  resources:
    - base:
        apiVersion: gcp.platformref.upbound.io/v1alpha1
        kind: XNetwork
      patches:
        - fromFieldPath: spec.id
          toFieldPath: spec.id
    - base:
        apiVersion: gcp.platformref.upbound.io/v1alpha1
        kind: XGKE
      connectionDetails:
        - fromConnectionSecretKey: kubeconfig
      patches:
        - fromFieldPath: spec.id
          toFieldPath: spec.id
        - fromFieldPath: metadata.uid
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-gke"
        - fromFieldPath: spec.writeConnectionSecretToRef.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        - fromFieldPath: spec.parameters.nodes.count
          toFieldPath: spec.parameters.nodes.count
        - fromFieldPath: spec.parameters.nodes.size
          toFieldPath: spec.parameters.nodes.size
        - fromFieldPath: spec.id
          toFieldPath: spec.parameters.XNetworkSelector.matchLabels[networks.gcp.platformref.upbound.io/network-id]
    - base:
        apiVersion: gcp.platformref.upbound.io/v1alpha1
        kind: XServices
      patches:
        - fromFieldPath: spec.id
          toFieldPath: spec.providerConfigRef.name
        - fromFieldPath: spec.parameters.services.operators.prometheus.version
          toFieldPath: spec.operators.prometheus.version
