apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: platform-ref-gcp
  annotations:
    meta.crossplane.io/maintainer:  Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/platform-ref-gcp
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This reference platform Configuration for Kubernetes and Data Services
      is a starting point to build, run, and operate your own internal cloud
      platform and offer a self-service console and API to your internal teams.

    meta.crossplane.io/readme: |
      This reference platform `Configuration` for Kubernetes and Data Services
      is a starting point to build, run, and operate your own internal cloud
      platform and offer a self-service console and API to your internal teams.

      It provides platform APIs to provision fully configured GKE clusters,
      with secure networking, and stateful cloud services (Cloud SQL) designed to
      securely connect to the nodes in each GKE cluster -- all composed using
      cloud service primitives from the [Upbound Official GCP
      Provider](https://marketplace.upbound.io/providers/upbound/provider-gcp). App
      deployments can securely connect to the infrastructure they need using
      secrets distributed directly to the app namespace.

      [Quickstart
      Guide](https://github.com/upbound/platform-ref-gcp/#quickstart)

      [Customize for your
      Organization](https://github.com/upbound/platform-ref-gcp/#customize-for-your-organization)

      To learn more checkout the [GitHub
      repo](https://github.com/upbound/platform-ref-gcp/) that you can copy and
      customize to meet the exact needs of your organization!
spec:
  crossplane:
    version: ">=v1.9.0-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-gcp
      version: ">=v0.13.0"
    - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
      version: ">=v0.12.0"
